name: Keep Render Alive

on:
  schedule:
    - cron: "*/15 * * * *"   # Her 15 dakikada bir çalışır
  workflow_dispatch:          # Manuel olarak da başlatılabilir

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
        run: |
          echo "Ping atılıyor..."
          curl -X GET https://akilli-doktor-asistani-buef.onrender.com/health
